# Generated by Django 4.2.4 on 2023-08-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_start', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
